##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - software-properties-common
    - build-essential 
    - libssl-dev 
    - libffi-dev 
    - python-dev
    - postgresql 
    - postgresql-contrib
    - virtualenv
    - redis-server
    

    

    
