##
# Set up Gunicorn and configure systemd to execute gunicorn_start script
##
- name: Create a deploy directory
  file: path={{ executable_dir }} state=directory
  become: yes

- name: Create a run socket directory for guinicorn
  file: path={{ app_dir }}/run state=directory
  become: yes

- name: Create the gunicorn_start script for running our app from systemd service
  template: src=gunicorn_start
                    dest={{ executable_dir }}/gunicorn_start
  become: yes

- name: Make the gunicorn_start script executable
  raw: cd {{ executable_dir }}; chmod +x gunicorn_start
  become: yes