- name: restart postgres
  service: name=postgresql state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: yes
  
- name: restart app
  service: name={{ app_name }} state=restarted enabled=yes
  become: yes

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
