# Generated by Django 2.2.8 on 2020-04-11 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toastmasters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 11, 9, 38, 10, 644635)),
            preserve_default=False,
        ),
    ]
