# Generated by Django 2.2.12 on 2020-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toastmasters', '0003_member_es_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='title',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
