# Generated by Django 2.2.12 on 2020-04-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toastmasters', '0004_auto_20200411_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberspeech',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
