# Generated by Django 2.2.12 on 2020-04-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toastmasters', '0005_auto_20200419_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathwaylevel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pathwayspeech',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
