# Generated by Django 2.2.12 on 2020-04-19 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toastmasters', '0008_auto_20200419_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberspeech',
            name='member',
            field=models.ForeignKey(default=2926, on_delete=django.db.models.deletion.CASCADE, to='toastmasters.Member'),
            preserve_default=False,
        ),
    ]
