# Generated by Django 2.2.12 on 2020-06-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toastmasters', '0009_memberspeech_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toastmasters.Meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toastmasters.Member')),
            ],
        ),
    ]
