##
# Run db migrations and get all static files
##
- name: Django check
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py check "
  

- name: Make migrations
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py makemigrations "
  
- name: Migrate database
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py migrate "
  

- name: Django collect static
  shell: ". {{ app_dir }}/.env; {{ venv_python }} {{ app_dir }}/manage.py collectstatic --noinput "




  